POST http://localhost:8080/login
Content-Type: application/json

{
    "username": "user1",
    "password": "password1"
}

###
GET http://localhost:8080/systemInfo

###
GET http://localhost:8080/users?id=john@doe251
Authorization: aabapuo247j

###
GET http://localhost:8080/users?namedf=J HTTP/1.1
Authorization: aabapuo247j

###
PUT http://localhost:8080/users HTTP/1.1
Authorization: aabapuo247j
Content-Type: application/json

{
    "name": "Jim Carry",
    "age": 23,
    "email": "jim.carry@example.com",
    "workingPosition": 2
}